name: ❓ Question
description: Ask a question about the repository or LLMOps
title: "[QUESTION] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help!

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: Your question here...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What is your question about?
      options:
        - General LLMOps concepts
        - Specific tool or resource
        - Contributing to the repository
        - Repository organization
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context
      placeholder: What have you tried? What are you trying to accomplish?
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues for similar questions
          required: true
        - label: I have read the [README](../../README.md)
          required: true
